name: mingler_app
description: socializing app
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  provider: ^4.0.2
  flutter_spinkit: ^4.1.1+1
  bottom_navy_bar: ^3.0.0
  contacts_service: ^0.3.9
  permission_handler: ^4.0.0
  spinner_input: ^0.1.2
  datetime_picker_formfield: ^0.4.3
  font_awesome_flutter: ^8.5.0
  transformer_page_view: ^0.1.6
  image_picker: ^0.6.2+3
  flushbar: ^1.9.1
  intl: ^0.15.5
  flutter_native_timezone: ^1.0.2
  timezone: ^0.5.2
  simple_gesture_detector: ^0.1.3
  flutter_launcher_icons: ^0.7.2+1
  geolocator: ^5.1.5
  synchronized: ^2.1.1
  firebase_core: ^0.4.0
  flutter_email_sender: ^2.2.2
  firebase_messaging: ^6.0.9
  firebase_admob: ^0.9.0+10
  flutter_colorpicker: ^0.2.6
  flutter_masked_text: ^0.8.0
  meta: ^1.1.6
  auto_size_text: ^2.0.0
  flutter_cupertino_settings: ^0.2.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/img1.jpg
  - assets/img2.jpg
  - assets/img3.jpg
  - assets/img4.jpg
  - assets/img5.jpg
  - assets/avatars/avatar-1.jpg
  - assets/avatars/avatar-2.jpg
  - assets/avatars/avatar-3.jpg
  - assets/avatars/avatar-4.jpg
  - assets/avatars/avatar-5.jpg
  - assets/avatars/avatar-6.jpg
